### ISSUE TITLE
us_lab.dae is an improper collada format that cannot be opened with meshlab or ctmviewer

### ISSUE THREAD

**Issue by pbeeson** [nasa/astrobee_media#1]
Despite loading in the ROS Collada loader, it is impossible to covert this dae using any other open-source collada programs, as there is something non-standard.  All the other ISS module meshes seem fine.

Meshlab bombs out on loading:
```
meshlab: ../../../../vcglib/wrap/io_trimesh/import_dae.h:395: static vcg::tri::io::UtilDAE::DAEError vcg::tri::io::ImporterDAE<OpenMeshType>::LoadTriangularMesh(QDomNodeList&, vcg::tri::io::ImporterDAE<OpenMeshType>::ColladaMesh&, size_t, vcg::tri::io::InfoDAE&, QMap<QString, QString>&) [with OpenMeshType = CMeshO; size_t = long unsigned int]: Assertion `indvt + offset < m.vert.size()' failed.
Aborted (core dumped)
```

In ctmviewer, this is how us_lab.dae looks:
![Screenshot from 2020-01-17 14-59-27](https://user-images.githubusercontent.com/3858374/72645767-fdab4300-3939-11ea-97df-bd94310d425f.png)

**Comment by pbeeson** [comment]
This did load in FreeCAD, so at least I can re-export to a second (textureless) .dae that is viewable by other programs.

**Comment by marinagmoreira** [comment]
Hi!
We usually use blender to edit the models, using the 2.83 version and the model opens correctly with the texture.
